export interface Destination {
  id: string;
  slug: string;
  name: string;
  country: string;
  continent: string;
  emoji: string;
  tagline: string;
  description: string;
  image: string;
  budgetPerDay: { min: number; max: number };
  currency: string;
  bestMonths: string[];
  tags: string[];
  coordinates: { lat: number; lng: number };
  trending: boolean;
  rating: number;
  reviewCount: number;
}

export const DESTINATIONS: Destination[] = [
  {
    id: "1",
    slug: "lisbonne",
    name: "Lisbonne",
    country: "Portugal",
    continent: "Europe",
    emoji: "🌊",
    tagline: "Soleil, pastéis et tramways rétro",
    description: "La capitale portugaise séduit par ses ruelles pavées, ses azulejos colorés et sa douceur de vivre méditerranéenne.",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 60, max: 120 },
    currency: "EUR",
    bestMonths: ["mars", "avril", "mai", "septembre", "octobre"],
    tags: ["Culture", "Gastronomie", "Architecture", "Vie nocturne"],
    coordinates: { lat: 38.7169, lng: -9.1399 },
    trending: true,
    rating: 4.8,
    reviewCount: 2847,
  },
  {
    id: "2",
    slug: "tokyo",
    name: "Tokyo",
    country: "Japon",
    continent: "Asie",
    emoji: "🗼",
    tagline: "Ultra-moderne et profondément traditionnel",
    description: "Tokyo mêle gratte-ciels futuristes, temples millénaires, gastronomie d'exception et pop culture inimitable.",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 80, max: 180 },
    currency: "JPY",
    bestMonths: ["mars", "avril", "octobre", "novembre"],
    tags: ["Culture", "Gastronomie", "Shopping", "Technologie"],
    coordinates: { lat: 35.6762, lng: 139.6503 },
    trending: true,
    rating: 4.9,
    reviewCount: 4521,
  },
  {
    id: "3",
    slug: "barcelone",
    name: "Barcelone",
    country: "Espagne",
    continent: "Europe",
    emoji: "🎨",
    tagline: "Art, plages et vie nocturne légendaire",
    description: "La ville de Gaudí vibre entre architecture surréaliste, plages méditerranéennes et tapas jusqu'à l'aube.",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 80, max: 150 },
    currency: "EUR",
    bestMonths: ["mai", "juin", "septembre", "octobre"],
    tags: ["Art", "Plages", "Gastronomie", "Architecture"],
    coordinates: { lat: 41.3851, lng: 2.1734 },
    trending: false,
    rating: 4.7,
    reviewCount: 3982,
  },
  {
    id: "4",
    slug: "bali",
    name: "Bali",
    country: "Indonésie",
    continent: "Asie",
    emoji: "🌴",
    tagline: "Rizières, temples et couchers de soleil magiques",
    description: "L'île des dieux offre un équilibre parfait entre spiritualité balinaise, surf, rizières en terrasses et plages paradisiaques.",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 40, max: 100 },
    currency: "IDR",
    bestMonths: ["avril", "mai", "juin", "juillet", "août", "septembre"],
    tags: ["Nature", "Spiritualité", "Surf", "Bien-être"],
    coordinates: { lat: -8.4095, lng: 115.1889 },
    trending: true,
    rating: 4.8,
    reviewCount: 5103,
  },
  {
    id: "5",
    slug: "rome",
    name: "Rome",
    country: "Italie",
    continent: "Europe",
    emoji: "🏛️",
    tagline: "L'histoire à chaque coin de rue",
    description: "La Ville Éternelle fascine par son patrimoine millénaire, sa gastronomie authentique et son art de vivre inimitable.",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 70, max: 150 },
    currency: "EUR",
    bestMonths: ["avril", "mai", "juin", "septembre", "octobre"],
    tags: ["Histoire", "Gastronomie", "Art", "Architecture"],
    coordinates: { lat: 41.9028, lng: 12.4964 },
    trending: false,
    rating: 4.7,
    reviewCount: 6241,
  },
  {
    id: "6",
    slug: "marrakech",
    name: "Marrakech",
    country: "Maroc",
    continent: "Afrique",
    emoji: "🕌",
    tagline: "Un labyrinthe de couleurs et d'épices",
    description: "La ville ocre envoûte par ses souks labyrinthiques, ses riads somptueux, sa cuisine parfumée et ses couchers de soleil sur l'Atlas.",
    image: "https://images.unsplash.com/photo-1539020140153-e479b8b22e78?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 35, max: 90 },
    currency: "MAD",
    bestMonths: ["mars", "avril", "octobre", "novembre"],
    tags: ["Culture", "Gastronomie", "Shopping", "Architecture"],
    coordinates: { lat: 31.6295, lng: -7.9811 },
    trending: true,
    rating: 4.6,
    reviewCount: 2183,
  },
  {
    id: "7",
    slug: "new-york",
    name: "New York",
    country: "États-Unis",
    continent: "Amérique",
    emoji: "🗽",
    tagline: "La ville qui ne dort jamais",
    description: "Manhattan, Brooklyn, Harlem — New York est une mosaïque de quartiers, une ville-monde qui donne l'impression de tout vivre en simultané.",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 120, max: 300 },
    currency: "USD",
    bestMonths: ["avril", "mai", "septembre", "octobre"],
    tags: ["Culture", "Gastronomie", "Shopping", "Art"],
    coordinates: { lat: 40.7128, lng: -74.006 },
    trending: false,
    rating: 4.8,
    reviewCount: 8912,
  },
  {
    id: "8",
    slug: "santorini",
    name: "Santorin",
    country: "Grèce",
    continent: "Europe",
    emoji: "🌅",
    tagline: "Maisons blanches et couchers de soleil légendaires",
    description: "L'archipel volcanique aux maisons bleues et blanches offre des panoramas à couper le souffle sur la caldeira et la mer Égée.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 100, max: 250 },
    currency: "EUR",
    bestMonths: ["mai", "juin", "septembre"],
    tags: ["Romance", "Plages", "Gastronomie", "Vues"],
    coordinates: { lat: 36.3932, lng: 25.4615 },
    trending: true,
    rating: 4.9,
    reviewCount: 3741,
  },
  {
    id: "9",
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Pays-Bas",
    continent: "Europe",
    emoji: "🚲",
    tagline: "Canaux, musées et liberté",
    description: "La capitale néerlandaise charme par ses canaux classés UNESCO, ses musées world-class, ses maisons penchées et son ambiance vélo.",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&h=800&fit=crop",
    budgetPerDay: { min: 90, max: 180 },
    currency: "EUR",
    bestMonths: ["avril", "mai", "juin", "juillet"],
    tags: ["Culture", "Musées", "Architecture", "Vélo"],
    coordinates: { lat: 52.3676, lng: 4.9041 },
    trending: false,
    rating: 4.7,
    reviewCount: 4128,
  },
];

export const DEMO_TRIPS = [
  {
    id: "demo-1",
    title: "5 jours à Lisbonne",
    destination: "Lisbonne",
    country: "Portugal",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&h=500&fit=crop",
    startDate: "2024-04-15",
    endDate: "2024-04-20",
    travelers: 2,
    budget: { total: 1240, spent: 980, currency: "EUR" },
    status: "completed",
    days: [
      {
        day: 1,
        title: "Arrivée & Alfama",
        activities: [
          { time: "15h00", name: "Check-in Rua das Flores Guest House", type: "hébergement", cost: 0 },
          { time: "17h00", name: "Ballade dans l'Alfama et le château São Jorge", type: "culture", cost: 10 },
          { time: "20h00", name: "Dîner au Time Out Market", type: "restaurant", cost: 25 },
        ],
      },
      {
        day: 2,
        title: "Belém & Pastéis",
        activities: [
          { time: "09h00", name: "Pastéis de Belém (les originaux !)", type: "gastronomie", cost: 5 },
          { time: "10h30", name: "Tour de Belém + Monastère des Jerónimos", type: "culture", cost: 20 },
          { time: "14h00", name: "MAAT Museum", type: "culture", cost: 12 },
          { time: "20h00", name: "Fado au Tasca do Chico", type: "culture", cost: 35 },
        ],
      },
    ],
    budgetBreakdown: {
      vols: 320,
      hébergement: 480,
      restaurants: 250,
      activités: 120,
      transport: 50,
      divers: 20,
    },
  },
  {
    id: "demo-2",
    title: "7 jours à Tokyo",
    destination: "Tokyo",
    country: "Japon",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=500&fit=crop",
    startDate: "2024-03-25",
    endDate: "2024-04-01",
    travelers: 1,
    budget: { total: 2100, spent: 1950, currency: "EUR" },
    status: "completed",
    days: [],
    budgetBreakdown: {
      vols: 750,
      hébergement: 560,
      restaurants: 350,
      activités: 220,
      transport: 150,
      divers: 70,
    },
  },
  {
    id: "demo-3",
    title: "4 jours à Barcelone",
    destination: "Barcelone",
    country: "Espagne",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=500&fit=crop",
    startDate: "2024-06-10",
    endDate: "2024-06-14",
    travelers: 3,
    budget: { total: 1800, spent: 0, currency: "EUR" },
    status: "upcoming",
    days: [],
    budgetBreakdown: {
      vols: 480,
      hébergement: 720,
      restaurants: 360,
      activités: 150,
      transport: 60,
      divers: 30,
    },
  },
];

export const BADGES = [
  { id: "first-trip", name: "Premier Envol", description: "Votre premier voyage planifié", emoji: "🚀", xp: 100 },
  { id: "foodie", name: "Foodie", description: "10 restaurants ajoutés à vos voyages", emoji: "🍽️", xp: 200 },
  { id: "europe-lover", name: "Européen de cœur", description: "5 pays européens visités", emoji: "🇪🇺", xp: 500 },
  { id: "solo-traveler", name: "Solo Rider", description: "Premier voyage en solo", emoji: "🎒", xp: 300 },
  { id: "beach-bum", name: "Beach Bum", description: "3 destinations balnéaires", emoji: "🏖️", xp: 250 },
  { id: "culture-vulture", name: "Culture Vulture", description: "20 musées visités", emoji: "🎨", xp: 400 },
  { id: "nightowl", name: "Night Owl", description: "Soirée jusqu'à l'aube dans 3 villes", emoji: "🦉", xp: 350 },
  { id: "local", name: "Le Local", description: "7+ jours dans la même ville", emoji: "🏠", xp: 600 },
];
